//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C_EgitimKampi301.EFProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Location
    {
        public int LocationID { get; set; }
        public string LocationCity { get; set; }
        public string LocationCountry { get; set; }
        public Nullable<byte> LocationCapacity { get; set; }
        public Nullable<decimal> LocationPrice { get; set; }
        public string DayNight { get; set; }
        public Nullable<int> GuideID { get; set; }
    
        public virtual Tbl_Guide Tbl_Guide { get; set; }
    }
}
